services:
  chat-producer1:
    build: ./chat-producer
    container_name: chat-producer1
    ports:
      - "8091:8090"
    environment:
      - INSTANCE_ID=producer1
    volumes:
      - ./chat-producer/src/main/resources/application.yml:/app/application.yml
    networks:
      - chatnet

  chat-producer2:
    build: ./chat-producer
    container_name: chat-producer2
    ports:
      - "8092:8090"
    environment:
      - INSTANCE_ID=producer2
    volumes:
      - ./chat-producer/src/main/resources/application.yml:/app/application.yml
    networks:
      - chatnet

  chat-producer3:
    build: ./chat-producer
    container_name: chat-producer3
    ports:
      - "8093:8090"
    environment:
      - INSTANCE_ID=producer3
    volumes:
      - ./chat-producer/src/main/resources/application.yml:/app/application.yml
    networks:
      - chatnet

  chat-consumer:
    build: ./chat-consumer
    container_name: chat-consumer
    ports:
      - "8094:8091"
    volumes:
      - ./chat-consumer/src/main/resources/application.yml:/app/application.yml
    networks:
      - chatnet


  nginx:
    image: nginx:latest
    container_name: local-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chat-producer1
      - chat-producer2
      - chat-producer3
      - chat-consumer
    networks:
      - chatnet

networks:
  chatnet:
