name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: chatting_msa  

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # --- Build chat-producer ---
      - name: Make gradlew executable (producer)
        run: chmod +x chatting_msa/chat-producer/gradlew

      - name: Build JAR for chat-producer
        run: cd chatting_msa/chat-producer && ./gradlew bootJar

      # --- Build chat-consumer ---
      - name: Make gradlew executable (consumer)
        run: chmod +x chatting_msa/chat-consumer/gradlew

      - name: Build JAR for chat-consumer
        run: cd chatting_msa/chat-consumer && ./gradlew bootJar

      # --- Debug: Check for built JARs ---
      - name: Debug — Check built files
        run: |
          echo "✅ Checking producer JAR..."
          ls -al chatting_msa/chat-producer/build/libs
          echo "✅ Checking consumer JAR..."
          ls -al chatting_msa/chat-consumer/build/libs

      # --- Copy files to EC2 ---
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: |
            chatting_msa/chat-producer/build/libs/app.jar
            chatting_msa/chat-consumer/build/libs/app.jar
            chatting_msa/docker-compose.yml
            chatting_msa/nginx/
            chatting_msa/chat-producer/
            chatting_msa/chat-consumer/
          target: "~/chat-app"

      # --- Remote deploy on EC2 ---
      - name: SSH and deploy with docker-compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/chat-app
            docker-compose down
            docker-compose up --build -d
