name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # --- Build chat-producer ---
      - name: Make gradlew executable (producer)
        run: chmod +x chat-producer/gradlew

      - name: Build JAR for chat-producer
        run: cd chat-producer && ./gradlew bootJar

      # --- Build chat-consumer ---
      - name: Make gradlew executable (consumer)
        run: chmod +x chat-consumer/gradlew

      - name: Build JAR for chat-consumer
        run: cd chat-consumer && ./gradlew bootJar

      # --- Copy files to EC2 ---
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: |
            chat-producer/build/libs/*.jar
            chat-consumer/build/libs/*.jar
            docker-compose.yml
            nginx/
            chat-producer/
            chat-consumer/
          target: "~/chat-app"

      # --- Remote deploy on EC2 ---
      - name: SSH and deploy with docker-compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/chat-app
            docker-compose down
            docker-compose up --build -d
